# Generated by Django 5.1.5 on 2025-02-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_alter_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
