# Generated by Django 5.1.5 on 2025-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('acc_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('alt_contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('gstin', models.CharField(max_length=20)),
                ('state_tax', models.BooleanField(default=True)),
                ('igst', models.BooleanField(default=True)),
                ('opening_balance', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
    ]
