# Generated by Django 5.1.5 on 2025-02-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
