# Generated by Django 5.1.5 on 2025-02-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('tax_applicable', models.BooleanField(default=False)),
                ('tax_rate', models.FloatField()),
                ('state_tax', models.BooleanField(default=True)),
                ('igst', models.BooleanField(default=True)),
                ('purchase_rate', models.FloatField()),
                ('selling_rate', models.FloatField()),
            ],
        ),
    ]
