# Generated by Django 5.1.5 on 2025-02-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
