# Generated by Django 5.1.5 on 2025-02-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Cashflow',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Gst',
        ),
        migrations.DeleteModel(
            name='Jobcard',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Sundry_creditors',
        ),
        migrations.DeleteModel(
            name='Sundry_debtors',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
