# Generated by Django 5.1.5 on 2025-02-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DjangoApp', '0009_delete_account_delete_bill_delete_cashflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('txn_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField()),
                ('date', models.DateField()),
                ('acc_type', models.CharField(max_length=10)),
                ('order_id', models.BigIntegerField()),
                ('vend_id', models.BigIntegerField()),
                ('taxable_total', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('discount', models.FloatField()),
                ('gtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('account', models.CharField(max_length=100)),
                ('ledger', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('cashflow', models.CharField(max_length=20)),
                ('cash_in', models.FloatField()),
                ('cash_out', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('acc_type', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('alt_contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('gstin', models.CharField(max_length=20)),
                ('taxable', models.BooleanField(default=True)),
                ('opening_balance', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('acc_type', models.CharField(max_length=10)),
                ('order_id', models.BigIntegerField()),
                ('cust_id', models.BigIntegerField()),
                ('taxable_total', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('discount', models.FloatField()),
                ('gtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_id', models.IntegerField()),
                ('added_at', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month_no', models.IntegerField()),
                ('month_name', models.CharField(max_length=25)),
                ('month_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.IntegerField()),
                ('acc_type', models.CharField(max_length=10)),
                ('item_no', models.SmallIntegerField()),
                ('product', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('qty', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('total', models.FloatField()),
                ('tax_rate', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('gtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('billno', models.IntegerField()),
                ('acc_type', models.CharField(max_length=10)),
                ('vend_id', models.BigIntegerField()),
                ('amount_paid', models.FloatField()),
                ('balance', models.FloatField()),
                ('payment_date', models.DateField(auto_now=True)),
                ('payment_no', models.BigIntegerField()),
                ('payment_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('tax_applicable', models.BooleanField(default=False)),
                ('tax_rate', models.FloatField()),
                ('state_tax', models.BooleanField(default=True)),
                ('igst', models.BooleanField(default=True)),
                ('purchase_rate', models.FloatField()),
                ('selling_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('jobno', models.IntegerField()),
                ('acc_type', models.CharField(max_length=10)),
                ('cust_id', models.BigIntegerField()),
                ('amount_received', models.FloatField()),
                ('balance', models.FloatField()),
                ('receipt_date', models.DateField(auto_now=True)),
                ('receipt_no', models.BigIntegerField()),
                ('payment_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sundry_creditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('vend_id', models.BigIntegerField()),
                ('voucher_no', models.IntegerField()),
                ('date', models.DateField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sundry_debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.BigIntegerField()),
                ('voucher_no', models.IntegerField()),
                ('date', models.DateField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('acc_type', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('alt_contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('gstin', models.CharField(max_length=20)),
                ('taxable', models.BooleanField(default=True)),
                ('opening_balance', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
    ]
