# Generated by Django 5.1.5 on 2025-02-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='added_at',
        ),
    ]
